language: node_js
node_js: stable
cache:
  directories:
    - node_modules
before_deploy:
  - npm run docs:build
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: ZAt9Mf3tAswfmjgu99BTzN0xyxg3C60dVeqnK9tOM8jiH3BpMKBGUH35iDbT66CWge4XM6pZIWA2ECMWmJfQScQJ2uE60/K55ncHC/FicunCG/Lqv6LZiJ8QIj7hrlVJv+A/p8+iBQquZNs0GbEoPSKLs2DS4BrjXFZ5MB3PjH5e4tCtY2sZFrjiB2BNQYl+XvL+Or0P5uCASnOmFpZbRnVomGSMqn0x7bMDthFaQ1y+kjJ/sCiPBRz6U+wjaGLDiveXOTbiaqyIQyxYHZraT94Kef+7Ezee4UPZzKRSL3Q0ISct202ooh8W63yqhDrWnSQhc7RuJGZABxVq6sAmMOg1JblYS4e31GV8nANZynDOLlYDkXv/MKWHIUEAijNrV3WWY47OYmkw5I3NjaqraiEptiLJ+lEmCjpg9ObnBohvphXi3nRgk3AmLrRFyYEHIlZ+NHdOqU8na6+t3ZUupVlhr+Tuq6R9rKMGhHf86XIpMmLJRhtPVKsd1EKp87ejurqT5a25eEnDrPQipnFMpvK406F5fVMxPypkWWyvSH+dquuHD9vME4mOzwtQeHsjRBagoN6yzSR8XM/LNJUUPfAemPONaG1nsQpbFESh+UXRzlLbrq5hq5gCTabciZXOP+6ASecwhzh+J258QzDboqJqQ1EimFXG0bXES+4ZKN4=
    app: qa-react-library
    on:
      branch: QA
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist-docs
    on:
      branch: master
